export default {
  showFooter: true,
  isSidebarCompact: false,
  showBreadcrumb: false,
  mode: localStorage.getItem('theme-mode') || 'auto',
  layout: 'side',
  splitMenu: false,
  isFooterAside: false,
  isSidebarFixed: true,
  isHeaderFixed: true,
  isUseTabsRouter: true,
  showHeader: true,
  backgroundTheme: 'blueGrey',
  brandTheme: 'default',
  title: 'HOUCLOUD-ADMIN 快速开发基础套件',
};
